on: [push]
name: build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build code
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: cmake -B build
    - name: Build
      shell: bash
      run: cmake --build build/
