on: [push]
name: build

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build code
    steps:
    - name: Install APT packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: sudo apt-get -yq install libxrandr-dev libglu1-mesa-dev libudev-dev libfreetype6-dev libalut-dev libvorbis-dev libflac-dev
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      shell: bash
      run: cmake -B build
    - name: Build
      shell: bash
      run: cmake --build build/
