on: [push]
name: build

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install APT packages
      if: matrix.platform == 'ubuntu-latest'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -yq install \
        libalut-dev \
        libflac-dev \
        libfreetype6-dev \
        libglu1-mesa-dev \
        libsfml-dev \
        libudev-dev \
        libvorbis-dev \
        libxrandr-dev
    - name: Install homebrew packages
      if: matrix.platform == 'macos-latest'
      run: brew install sfml
    - name: Download and extract SFML
      if: matrix.platform == 'windows-latest'
      run: |
        curl -OL https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
        unzip SFML-2.5.1-windows-vc15-64-bit.zip
        echo "SFML_ROOT=$(pwd)/SFML-2.5.1" >> $GITHUB_ENV
    - name: Configure
      run: cmake -DSFML_ROOT=${SFML_ROOT} -B build
    - name: Build
      run: cmake --build build/
